services:
  postgres:
    image: postgres:15
    container_name: blognest-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: blognest_user
      POSTGRES_PASSWORD: blognest_pass
      POSTGRES_DB: blognest_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blognest-net

volumes:
  postgres_data:

networks:
  blognest-net:
    driver: bridge
